name: Snyk Code Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  snyk-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master

      - name: Run Snyk Code (SAST) scan
        run: snyk code test --sarif-file-output=snyk-code.sarif
        env:
          SNYK_TOKEN: 268898ef-00bd-4d1f-a3ed-8b101f14d379

      - name: Upload results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif

        
